import { useState } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";

import MultiSelectDropbox from "@/components/shared/MultiSelectDropbox/MultiSelectDropbox";

import styles from "@/styles/Home.module.scss";

const inter = Inter({ subsets: ["latin"] });

const items = [
  { id: 1, name: "Apple" },
  { id: 2, name: "Carrot" },
  { id: 3, name: "Melone" },
  { id: 4, name: "Pear" },
  { id: 5, name: "Lemon" },
  { id: 6, name: "Orange" },
  { id: 7, name: "Salad" },
];

export default function Home() {
  const [itemsList, setItemsList] = useState(items);

  const handleClickDropboxItem = (itemObj) => {
    setItemsList((prevItemList) =>
      prevItemList.filter((item) => item.id !== itemObj.id)
    );
  };

  return (
    <>
      <Head>
        <title>web3m-test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <MultiSelectDropbox
          dataList={itemsList}
          placeholderText="Select to add item to basket"
          handleClick={handleClickDropboxItem}
        />
      </main>
    </>
  );
}
